package com.dwl.common.enums.quality;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * 测试报告类型枚举
 * <p>
 * Test Report Type Enumeration
 * <p>
 * 用于表示测试报告的来源类型。
 * <p>
 * Used to represent the source type of a test report.
 *
 * @Author Dwl
 * @Version 1.0
 * @Since 2026-08-26 23:50
 */
@Getter
@AllArgsConstructor
@Schema(description = """
        测试报告类型
        Test Report Type
        """)
public enum ReportType {

    /**
     * 任务报告 - 由测试任务生成的报告
     * Task report - report generated by test task
     */
    TASK("task", "任务报告"),

    /**
     * 链路报告 - 由业务链路测试生成的报告
     * Link report - report generated by business link testing
     */
    LINK("link", "链路报告"),

    /**
     * 变更报告 - 由代码变更分析触发生成的报告
     * Change report - report generated by code change analysis
     */
    CHANGE("change", "变更报告");

    /**
     * Type code
     */
    @Schema(description = """
            Type code
            """, example = "task")
    private final String code;

    /**
     * Chinese description
     */
    @Schema(description = """
            Chinese description
            """, example = "任务报告")
    private final String description;

    /**
     * Get enum by code
     *
     * @param code Type code
     * @return ReportType enum, or null if not found
     */
    public static ReportType of(String code) {
        for (ReportType rt : values()) {
            if (rt.code.equals(code)) {
                return rt;
            }
        }
        return null;
    }

}
