<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.dwl</groupId>
        <artifactId>automated-test-platform-service</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>automated-test-platform-dao</artifactId>
    <packaging>jar</packaging>
    <name>Automated Test Platform Dao</name>
    <description>数据访问模块 - Mapper接口、XML映射文件</description>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <!--
        内部模块
        Internal Modules
        -->
        <dependency>
            <groupId>com.dwl</groupId>
            <artifactId>automated-test-platform-model</artifactId>
        </dependency>

        <!--
        MyBatis-Plus
        ORM增强
        -->
        <dependency>
            <groupId>com.baomidou</groupId>
            <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        </dependency>

        <!--
        Lombok
        -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>

    </dependencies>

</project>