package com.dwl.common.base;


import com.baomidou.mybatisplus.annotation.*;
import com.dwl.common.enums.DeletedStatus;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Base Entity Class
 * <p>
 * 所有数据库实体的公共父类, 包含主键, 逻辑删除标识和审计时间字段
 * <p>
 * Common parent class for all database entities, containing primary key id, 
 * logical delete flag and audit timestamp fields
 *
 * @Author Dwl
 * @Version 1.0
 * @Since 2026-08-05 18:17
 */
@Data
@Schema(description = """
        Base Entity Class
        """)
public abstract class BaseEntity implements Serializable {

    @Serial
    private static final long serialVersionUID = 1L;


    @Schema(description = """
            Primary key id
            雪花算法生成 (generated by snowflake algorithm)
            """, example = "1234567890123456789")
    @TableId(type = IdType.ASSIGN_ID)
    private Long id;

    @Schema(description = """
            逻辑删除标识
            Logical delete flag
            """, 
            example = "0", 
            implementation = DeletedStatus.class)
    @TableLogic
    private Integer isDelete;

    @Schema(description = """
            Creation time (auto-filled on insert)
            """, example = "2026-08-05T00:00:00")
    @TableField(fill = FieldFill.INSERT)
    private LocalDateTime createdAt;

    @Schema(description = """
            Update time (auto-filled on insert and update)
            """, example = "2026-08-05T00:00:00")
    @TableField(fill = FieldFill.INSERT_UPDATE)
    private LocalDateTime updatedAt;
}
